security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Client:
            algorithm: auto # You can specify the algorithm you prefer, such as bcrypt
    providers:
        # Assuming you have a custom UserProvider for your Client entity
        # Adjust this according to your actual user provider configuration
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: email # Property to use as the username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider # Use the custom user provider for clients
            # Configure your authentication methods here, such as form_login, remember_me, etc.
            # Adjust this according to your authentication requirements
            # See: https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
            # Example:
            # form_login:
            #     login_path: app_login
            #     check_path: app_login
            #     default_target_path: app_homepage
            # logout:
            #     path: app_logout
            #     target: app_homepage

    # Access control rules
    access_control:
        # Adjust access control rules according to your application's needs
        # Example:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
