#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
add_card:
    path: /addcard/{id}
    controller: App\Controller\OffreController::addcard
    methods: ['GET']
